name: Tweet on push to main

on:
  push:
    branches:
      - main

env:
  TWEET_CONTENT: ""

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run Python script
        run: |
          python tweet.py > tweet_content.txt
          echo "::set-env name=TWEET_CONTENT::$(cat tweet_content.txt)"

      - name: Tweet
        uses: actions/twitter/tweet@v2
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        with:
          message: ${{ env.TWEET_CONTENT }}
