name: Tweet on push

on:
  push:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      env:
        MESSAGE: "Hello, this is a tweet from GitHub Actions!"
    - name: tweet
      uses: peter-evans/tweet-action@v2
      with:
        args: ${{ env.MESSAGE }}
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
